package com.gtalee.covert;

import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;
import javax.imageio.ImageIO;

/** UTF-8 new core: creates a base image, difference patches, and a compose properties file. */
public final class FramePatchComposeBuilder {
  public static final class Result { public int frameCount, patchCount; public File base; public List<File> patches=new ArrayList<File>(); }
  private FramePatchComposeBuilder() {}
  public static Result build(File input, File output, int threshold, int gap, int minPixels, int maxPatch) throws IOException {
    File[] fs=input.listFiles(new FilenameFilter(){public boolean accept(File d,String n){String x=n.toLowerCase();return x.endsWith(".png")||x.endsWith(".jpg")||x.endsWith(".jpeg");}});
    if(fs==null||fs.length==0) throw new IOException("no input images"); Arrays.sort(fs); if(!output.exists()&&!output.mkdirs())throw new IOException("cannot create output");
    BufferedImage base=ImageIO.read(fs[0]); Result r=new Result();r.frameCount=fs.length;r.base=new File(output,"base.png");ImageIO.write(base,"png",r.base);
    Properties p=new Properties();p.setProperty("format","frame-patch-v1");p.setProperty("frames",String.valueOf(fs.length));p.setProperty("base","base.png");
    for(int fi=0;fi<fs.length;fi++){BufferedImage im=ImageIO.read(fs[fi]);if(im.getWidth()!=base.getWidth()||im.getHeight()!=base.getHeight())throw new IOException("输入的图片尺寸不一致，请更换为相同尺寸的图片");List<String> refs=new ArrayList<String>();
      for(int y=0;y<base.getHeight();y+=maxPatch) for(int x=0;x<base.getWidth();x+=maxPatch){int w=Math.min(maxPatch,base.getWidth()-x),h=Math.min(maxPatch,base.getHeight()-y),n=0;for(int yy=0;yy<h;yy++)for(int xx=0;xx<w;xx++)if(diff(base.getRGB(x+xx,y+yy),im.getRGB(x+xx,y+yy),threshold))n++;if(n<minPixels)continue;BufferedImage patch=new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);for(int yy=0;yy<h;yy++)for(int xx=0;xx<w;xx++)patch.setRGB(xx,yy,im.getRGB(x+xx,y+yy));String name=String.format("patch_%04d.png",r.patchCount++);File out=new File(output,name);ImageIO.write(patch,"png",out);r.patches.add(out);refs.add(name+"@"+x+","+y);}
      p.setProperty("frame."+fi,refs.size()==0?"":join(refs)); }
    FileOutputStream os=new FileOutputStream(new File(output,"frame_patches.compose.properties"));p.store(os,"Generated by PipImageCovert");os.close();return r;
  }
  private static String join(List<String> a){StringBuilder s=new StringBuilder();for(String x:a){if(s.length()>0)s.append(';');s.append(x);}return s.toString();}
  private static boolean diff(int a,int b,int t){int ar=(a>>16)&255,ag=(a>>8)&255,ab=a&255,br=(b>>16)&255,bg=(b>>8)&255,bb=b&255;return Math.max(Math.max(Math.abs(ar-br),Math.abs(ag-bg)),Math.abs(ab-bb))>t||((a>>>24)&255)!=((b>>>24)&255);}
}
